### ISSUE TITLE
`ComparHelper` CI currently now working

### ISSUE THREAD

**Issue by facusapienza21** [ODINN-SciML/SphereUDE.jl#7]
I am not sure why this is not working, but I think is either because: 
- There is still something to be done with the PyCall integration in the setup of the package that CompatHelper is still not capturing. 
- We need to define the corresponding GH secret for this action. I am leaning towards this option, but double-checking on the `ODINN.jl` package there is no secret defined for this action: 
```
name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
```
@JordiBolibar do you have any insight on this?
